Lab5/Lab5/Models/ErrorViewModel.cs
using System;

namespace Lab5.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab5/Lab5/Models/PeliculaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lab5.Models
{
    public class PeliculaModel
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Duracion { get; set; }
        public string Categoria { get; set; }
        public string Clasificacion { get; set; }
    }
}

Lab5/Lab5/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Lab5.Models;

namespace Lab5.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab5/Lab5/Controllers/PeliculasController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.SqlServer.Server;

namespace Lab5.Controllers
{
    public class PeliculasController : Controller
    {
        string connection = "Data Source= database-1.c0pmfzscntnx.us-east-1.rds.amazonaws.com,1433 ;Initial Catalog= Lab_Virtualizacion ;User ID= admin; Password= iRdCsjCWDLTnxs0OdLb4;";
        // GET: Peliculas
        public ActionResult Index()
        {
            List<Models.PeliculaModel> PeliculasLista = new List<Models.PeliculaModel>();

            SqlConnection sqlconnection = new SqlConnection(connection);

            string query = "Select * from Peliculas";

            sqlconnection.Open();

            SqlCommand sqlCommand = new SqlCommand(query, sqlconnection);

            SqlDataReader sqlDataReader = sqlCommand.ExecuteReader();

            while (sqlDataReader.Read())
            {
                Models.PeliculaModel pelicula = new Models.PeliculaModel();
                pelicula.ID = sqlDataReader.GetInt32(0);
                pelicula.Nombre = sqlDataReader.GetString(1);
                pelicula.Duracion = sqlDataReader.GetString(2);
                pelicula.Clasificacion = sqlDataReader.GetString(3);
                pelicula.Categoria = sqlDataReader.GetString(4);
                PeliculasLista.Add(pelicula);
            }
            sqlconnection.Close();
            IEnumerable<Models.PeliculaModel> peliculaModels = PeliculasLista;
            return View(peliculaModels);
        }

        // GET: Peliculas/Details/5
        public ActionResult Details(int id)
        {
            SqlConnection sqlconnection = new SqlConnection(connection);

            string query = "Select * from Peliculas where ID = '" + id + "';";

            sqlconnection.Open();

            SqlCommand sqlCommand = new SqlCommand(query, sqlconnection);

            SqlDataReader sqlDataReader = sqlCommand.ExecuteReader();
            Models.PeliculaModel pelicula = new Models.PeliculaModel();
            while (sqlDataReader.Read())
            {

                pelicula.ID = sqlDataReader.GetInt32(0);
                pelicula.Nombre = sqlDataReader.GetString(1);
                pelicula.Duracion = sqlDataReader.GetString(2);
                pelicula.Clasificacion = sqlDataReader.GetString(3);
                pelicula.Categoria = sqlDataReader.GetString(4);

            }
            sqlconnection.Close();
            return View(pelicula);
        }

        // GET: Peliculas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Peliculas/Create
        [HttpPost]
        public ActionResult Create(Models.PeliculaModel collection)
        {
            try
            {
                SqlConnection sqlconnection = new SqlConnection(connection);

                string query = "INSERT INTO [dbo].[PELICULAS] ([Nombre],[Duracion],[Tipo],[Categoria]) VALUES ('" + collection.Nombre + "','" + collection.Duracion + "','" + collection.Clasificacion + "','" + collection.Categoria + "');";
                sqlconnection.Open();
                SqlCommand sqlCommand = new SqlCommand(query, sqlconnection);
                sqlCommand.ExecuteNonQuery();
                sqlconnection.Close();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Peliculas/Edit/5
        public ActionResult Edit(int id)
        {
            SqlConnection sqlconnection = new SqlConnection(connection);

            string query = "Select * from Peliculas where ID = '" + id + "';";

            sqlconnection.Open();

            SqlCommand sqlCommand = new SqlCommand(query, sqlconnection);

            SqlDataReader sqlDataReader = sqlCommand.ExecuteReader();
            Models.PeliculaModel pelicula = new Models.PeliculaModel();
            while (sqlDataReader.Read())
            {

                pelicula.ID = sqlDataReader.GetInt32(0);
                pelicula.Nombre = sqlDataReader.GetString(1);
                pelicula.Duracion = sqlDataReader.GetString(2);
                pelicula.Clasificacion = sqlDataReader.GetString(3);
                pelicula.Categoria = sqlDataReader.GetString(4);

            }
            sqlconnection.Close();
            return View(pelicula);
        }

        // POST: Peliculas/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Models.PeliculaModel collection)
        {
            try
            {
                SqlConnection sqlconnection = new SqlConnection(connection);

                string query = "UPDATE [dbo].[PELICULAS]SET [Nombre] = '" + collection.Nombre + "',[Duracion] = '" + collection.Duracion + "',[Tipo] = '" + collection.Clasificacion + "',[Categoria] = '" + collection.Categoria + "' WHERE [ID] = '" + collection.ID + "';";
                sqlconnection.Open();
                SqlCommand sqlCommand = new SqlCommand(query, sqlconnection);
                sqlCommand.ExecuteNonQuery();
                sqlconnection.Close();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Peliculas/Delete/5
        public ActionResult Delete(int id)
        {
            SqlConnection sqlconnection = new SqlConnection(connection);

            string query = "Select * from Peliculas where ID = '" + id + "';";

            sqlconnection.Open();

            SqlCommand sqlCommand = new SqlCommand(query, sqlconnection);

            SqlDataReader sqlDataReader = sqlCommand.ExecuteReader();
            Models.PeliculaModel pelicula = new Models.PeliculaModel();
            while (sqlDataReader.Read())
            {

                pelicula.ID = sqlDataReader.GetInt32(0);
                pelicula.Nombre = sqlDataReader.GetString(1);
                pelicula.Duracion = sqlDataReader.GetString(2);
                pelicula.Clasificacion = sqlDataReader.GetString(3);
                pelicula.Categoria = sqlDataReader.GetString(4);

            }
            sqlconnection.Close();
            return View(pelicula);
        }

        // POST: Peliculas/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                SqlConnection sqlconnection = new SqlConnection(connection);

                string query = "DELETE FROM [dbo].[PELICULAS] WHERE [ID]= '" + id + "';";

                sqlconnection.Open();

                SqlCommand sqlCommand = new SqlCommand(query, sqlconnection);

                sqlCommand.ExecuteNonQuery();
                Models.PeliculaModel pelicula = new Models.PeliculaModel();
                sqlconnection.Close();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Lab5/Lab5/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Lab5/Lab5/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Lab5/Lab5/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Lab5/Lab5/Views/Peliculas/Create.cshtml
@model Lab5.Models.PeliculaModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>PeliculaModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duracion" class="control-label"></label>
                <input asp-for="Duracion" class="form-control" />
                <span asp-validation-for="Duracion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Categoria" class="control-label"></label>
                <input asp-for="Categoria" class="form-control" />
                <span asp-validation-for="Categoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Clasificacion" class="control-label"></label>
                <input asp-for="Clasificacion" class="form-control" />
                <span asp-validation-for="Clasificacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lab5/Lab5/Views/Peliculas/Delete.cshtml
@model Lab5.Models.PeliculaModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PeliculaModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Duracion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Duracion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Categoria)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Clasificacion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Clasificacion)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Lab5/Lab5/Views/Peliculas/Details.cshtml
@model Lab5.Models.PeliculaModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>PeliculaModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Duracion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Duracion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Categoria)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Clasificacion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Clasificacion)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    <a asp-action="Index">Back to List</a>
</div>

Lab5/Lab5/Views/Peliculas/Edit.cshtml
@model Lab5.Models.PeliculaModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>PeliculaModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duracion" class="control-label"></label>
                <input asp-for="Duracion" class="form-control" />
                <span asp-validation-for="Duracion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Categoria" class="control-label"></label>
                <input asp-for="Categoria" class="form-control" />
                <span asp-validation-for="Categoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Clasificacion" class="control-label"></label>
                <input asp-for="Clasificacion" class="form-control" />
                <span asp-validation-for="Clasificacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lab5/Lab5/Views/Peliculas/Index.cshtml
@model IEnumerable<Lab5.Models.PeliculaModel>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duracion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Categoria)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Clasificacion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Duracion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Categoria)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Clasificacion)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            </tr>
        }
    </tbody>
</table>

Lab5/Lab5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab5</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Peliculas" asp-action="Index" class="navbar-brand">Lab5 Peliculas</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Lab5</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>